### ISSUE TITLE
How can i use this script package that used cocoapods generate workspace?

### ISSUE THREAD

**Issue by flynio** [lexrus/ios-makefile#11]
i try to package cocoapds workspace,but it failed.

ld: library not found for -lPods
The following build commands failed:
    Ld build/xxxx.build/Release-iphoneos/xxxx.build/Objects-normal/armv7/nva normal armv7
    Ld build/xxxx.build/Release-iphoneos/xxx.build/Objects-normal/armv7s/nva normal armv7s

how can i fix it? thank you!

**Comment by lexrus** [comment]
Try to comment this line:
https://github.com/lexrus/ios-makefile/blob/master/makefile.cfg#L7
