### ISSUE TITLE
关于7.1下打包需要下载需要支持https协议

### ISSUE THREAD

**Issue by wwwang89** [lexrus/ios-makefile#12]
你好！请问一下，我可以实现自动打包，但是现在在7.1的系统下必须支持https的协议下载才行，现在自动打包是http的，我需要怎么样才能支持https的呢？O(∩_∩)O谢谢

**Comment by lexrus** [comment]
就我所知只要 plist 是在 https 上就可以了。
建 https 的方法之后我会补充在 readme 里。

**Comment by wwwang89** [comment]
恩，好的，谢谢了 ，你那边能不能分享几个上传到免费的htttps协议的虚拟服务器上在配置文件里面，非常感谢！

**Comment by lexrus** [comment]
你好，我更新了 makefile，现在 `make serve` 会自动生成一个自签名的 SSL 证书用于建立 HTTPS 协议的 web 服务，另外需要在 makefile.cfg 中把 "http" 改成 "https"。
关于在虚拟机上建 HTTPS，生成证书的步骤基本和 makefile 中用到的方法一样，但是不同的 Linux 发行版和不同的 web server 都会有不同的设置。我比较习惯用 Debian 的 Nginx 默认配置。
