### ISSUE TITLE
部分设备提示无法连接xxx.local

### ISSUE THREAD

**Issue by demonnico** [lexrus/ios-makefile#15]
同事有一台iPhone5s，一台iPhone5c提示该错误。系统7.1+
如题
证书已成功安装后
之后点击提示无法连接`xxx.local`
求头绪

**Comment by lexrus** [comment]
介于 Bonjour 网络环境的不确定性，建议遇到这种问题还是放外网或用 IP 访问，不算是本 makefile 的问题，先关了。

**Comment by demonnico** [comment]
@lexrus
Roger.
