### ISSUE TITLE
多个target编译命令的问题

### ISSUE THREAD

**Issue by soulin** [lexrus/ios-makefile#17]
你好，我在终端进入my_test_projec目录后执行make,rake,rake second 这三个命令都报 make: **\* /Users/xx/Downloads/ios-makefile-master: Is a directory.  Stop.
这个错，该怎么解决啊？

**Comment by lexrus** [comment]
请检查一下配置文件每行结尾有没有多余的空格。

**Comment by soulin** [comment]
@lexrus 我是用你github上的工程来 试的啊

**Comment by soulin** [comment]
@lexrus 找到原因了。。之前我ios-makefile-master3  这个文件名称有个空格

**Comment by soulin** [comment]
@lexrus 再次拜谢！
