### ISSUE TITLE
make命令报warning: NUL character seen; rest of line ignored

### ISSUE THREAD

**Issue by soulin** [lexrus/ios-makefile#18]
make
makefile:1: warning: NUL character seen; rest of line ignored
# makefile:1: **\* missing separator.  Stop.

请问这个改怎么解决啊？

**Comment by lexrus** [comment]
用 `make --debug=v` 看一下哪里错了。

**Comment by soulin** [comment]
This program built for i386-apple-darwin11.3.0
Reading makefiles...
Reading makefile `makefile'...
makefile:1: warning: NUL character seen; rest of line ignored
makefile:1: **\* missing separator.  Stop.

**Comment by soulin** [comment]
请问这是什么原因啊

**Comment by lexrus** [comment]
你把 cfg 贴上来看看，注意去掉敏感信息。

**Comment by soulin** [comment]
很奇怪啊，我把工程 拷贝到其他目录就可以 编译打包成功了

**Comment by soulin** [comment]
APP          = Mxxx

# Leave this blank while building project

WORKSPACE    =

# Specify project name if there's no WORKSPACE

PROJECT      = Mxxx

CONFIG       = Release
SCHEME       = Mxxx
ICON_TAG     = YES

# iMessage addresses list seperated with white space

#IMSG_LIST    = a_imessage_email@mac.com +86.18621800000 another_email@me.com

# Comment the following line if you prefer Bonjour Network

# BASE_URL     = https://ota.yourserver.com

# Your Mailgun mail list

#EMAIL_LIST   = newproject@yourid.mailgun.org
#EMAIL_DOMAIN = yourid.mailgun.org

# Get API key from Keychain by item name "mailgun api key"

#MAILGUN_API_KEY = $(shell security find-generic-password -l "mailgun api key" -gw)

# Your server with SSH access

#SFTP_SERVER  = root@yourserver.com
#SFTP_PATH    = /var/www/ota
#SFTP_PORT    = 22

# Share via Apple Bonjour Network

#BASE_PORT    = 9966
#BASE_URL    ?= https://$(shell scutil --get ComputerName).local:$(BASE_PORT)

# Shorten URL by lexr.us

# Change or comment this line if you prefer goo.gl

#LEXR_US      = NO

# TestFlight Tokens

#TESTFLIGHT_API_TOKEN  = GET_IT_FROM__https://testflightapp.com/account/#api
#TESTFLIGHT_TEAM_TOKEN = GET_IT_FROM__https://testflightapp.com/dashboard/team/edit/

# HockeyApp Token

#HOCKEY_APP_API_TOKEN  = GET_IT_FROM__https://rink.hockeyapp.net/manage/auth_tokens

这是我的cfg文件

**Comment by soulin** [comment]
/Users/xx/Documents/workspace/xxx/project/Mxxx  这是我一开始的目录
然后我改成
/Users/xx/Documents/workspace/xxx/project1/Mxxx
就打包成功了，很文件夹目录有关系吗。。

**Comment by lexrus** [comment]
呃，不明觉历。

**Comment by soulin** [comment]
囧，我改目录名称了，正常了，谢谢！

**Comment by soulin** [comment]
还有个很奇怪的问题，我的工程目录下一定要放makefile的源文件，不能放makefile的替身快捷方式，不然make会报 
makefile:1: warning: NUL character seen; rest of line ignored
makefile:1: **\* missing separator.  Stop.

**Comment by lexrus** [comment]
你试试 unlink 后再重新 ln -s 一下。

**Comment by l1uchao** [comment]
@soulin 你好，你的问题怎么解决的？我遇到了这一问题，不知道怎么解决。
