### ISSUE TITLE
多个 Target 如何编译指定程序

### ISSUE THREAD

**Issue by zhugexiaobo** [lexrus/ios-makefile#9]
如题

**Comment by lexrus** [comment]
你可以暂时改一下 makefile，在 xcodebuild 那段加上 -target TARGET_NAME。
我考虑在下一版里加上这个配置。

**Comment by wwwang89** [comment]
哦，可以中文？呵呵，你好！请问一下，我可以实现自动打包，但是现在在7.1的系统下必须支持https的协议下载才行，现在自动打包是http的，我需要怎么样才能支持https的呢？O(∩_∩)O谢谢

**Comment by lexrus** [comment]
@wwwang89 
HTTPS 的问题早就解决了。

@zhugexiaobo @soulin
你们觉得配置里用豆号分隔多个 target 和 scheme 怎么样? 不过这样脚本会复杂好多。

**Comment by soulin** [comment]
@lexrus 感觉用逗号分隔好啊，会麻烦很多吗？

**Comment by soulin** [comment]
@lexrus 
多个target时候，我的只能编译通过工程一开始默认建立的target，
其他target会编译完打包时会报错，该怎么解决啊？
Print: Entry, ":CFBundleDisplayName", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Parse Error: Unclosed Quotes
Print: Entry, ":CFBundleIdentifier", Does Not Exist
Parse Error: Unclosed Quotes
Print: Entry, ":CFBundleDisplayName", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Print: Entry, ":CFBundleDisplayName", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist

**Comment by lexrus** [comment]
@soulin 
这几个错是说从 plist 里取 App 信息的时候没有找到对应 target 的 plist 的文件。默认 target 的名字就是 App 名，所以能编译通过。
https://github.com/lexrus/ios-makefile/blob/master/makefile#L45-L49

逗号分隔我试了一下，还是比较麻烦的，我在试一个更省事的做法。

**Comment by lexrus** [comment]
写 N 个 cfg 文件，然后符号链接切换要编译哪一个，makefile 里加了 build_target。
我写了个例子：
https://github.com/lexrus/ios-makefile/blob/master/my_test_project/Rakefile

用的时候 `rake` 或 `rake second`。

**Comment by soulin** [comment]
@lexrus 多谢啊！
